### ISSUE TITLE
Is this still maintained or it works flawlessly on webgl already?

### ISSUE THREAD

**Issue by tfgstudios** [snarlynarwhal/unity-websockets-for-webgl#1]
Hi, I just want to make sure I'm using a error-free solution for my webgl project, which will become very complex in time. Can you tell me if this lib supports raw bytes sending/receiving and that it's bug-free?

Thank you for sharing this code with the community :)

**Comment by snarlynarwhal** [comment]
It should still function just fine! Do not hesitate to post any issues that arise during development. Keep in mind that this has only been tested on WebGL and Desktop builds.

Take a look at [EchoExample.cs ](https://github.com/snarlynarwhal/Unity-WebSockets-For-WebGL/blob/master/Assets/Plugins/UnityWebSocketsForWebGL/EchoExample.cs)- it supports sending/receiving bytes.

Keep in mind that these callbacks do not occur in the main thread. You cannot make Unity api calls in secondary threads - attempting to do so throws an error. So make a thread safe event queue to push the messages to the main thread and execute them there like so:

**NOTE:** *The `EventManager` and `GameEvent` classes do not exist in this project - just using them as an example.*

```C#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EventManager : MonoBehaviour {

	public static EventManager Instance { get; private set; }
	private static readonly object padlock = new object();
	private Queue<GameEvent> queuedEvents = new Queue<GameEvent>();

	private void Awake() {
		if (Instance != null){
			Destroy(this);
		}
		Instance = this;
	}

	private void FixedUpdate() {
		lock (padlock) {
			while (queuedEvents.Count > 0) {
				queuedEvents.Dequeue().Execute();
			}
		}
	}

	public static void Enqueue<T>(T gameEvent) where T : GameEvent {
		Instance.enqueue<T>(gameEvent );
	}

	private void enqueue<T>(T gameEvent) where T : GameEvent {
		lock (padlock){
			queuedEvents.Enqueue(e);
		}
	}
}
```

In the `WebSocket_OnMessage` callback, you can deserialize the message and add it to the event queue:

```C#
GameEvent gameEvent = // deserialized data
EventManager.Enqueue<GameEvent >(gameEvent);
```

Closing - feel free to reopen if you have more questions or run into issues.
